CREATE TABLE SAIMK.ALPHABETS
(LANGUAGE VARCHAR2(256), CHARACTER VARCHAR2(3), ORDER_NO NUMBER, DEPRECATED CHAR(1) DEFAULT 'N')
;

GRANT SELECT ON SAIMK.ALPHABETS TO PUBLIC;

SELECT * FROM  SAIMK.ALPHABETS;

INSERT INTO SAIMK.ALPHABETS
(
SELECT 'ENGLISH', CHR(ROWNUM + 64), ROWNUM, 'N' FROM ALL_OBJECTS AO WHERE ROWNUM < 27
)
;

COMMIT;